import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideMenu from "@/components/sidemenu/Sidemenu";
import Navbar from "@/components/navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ahemd Masroor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          <SideMenu />
          <div className="flex-1">
            <Navbar />
            <main className="p-4 bg-gray-700 min-h-screen relative">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
